### ISSUE TITLE
Trapped chests

### ISSUE THREAD

**Issue by Drexell** [RednedEpic/PhatLoots#1]
Hello I posted about this earlier but I wanted to let you know that trapped chests dont receive a redstone signal or chest animation if it is linked to a phatloot table.  If this could be fixed it would solve a really big issue im having right now.  Other then that this is a great plugin and seems to work great otherwise.

**Comment by RednedEpic** [comment]
How exactly would that work? Would the chest only show an animation or would something also happen with all that is in the loot table?

**Comment by Drexell** [comment]
basicly i have  room witha  puzzle in it. you do the puzzle then gain access to the chest.  when the chest opens phatloots does its things and gives the player random loot from a loot table. but i need the trapped chest its linked to to set off the redstone signal like it normally would as it sets off a reset for my puzzle room.

**Comment by Drexell** [comment]
Would be more then happy to show you the room and its configuration just give me the word and ill send you info  :D

**Comment by RednedEpic** [comment]
So you're saying it doesn't activate a redstone signal if it's linked to a PhatLoot like a normal trapped chest would?

**Comment by Drexell** [comment]
correct.

**Comment by RednedEpic** [comment]
Alright, I'll see if I can implement a way for this to be added. Currently the way PhatLoots is setup is that it entirely cancels the event when a player clicks a chest which I'd assume Codisimus put in there to keep the player from opening up the normal chest inventory. However due to this, the other part(s) of the event are cancelled too, which is why no redstone signal is being created.

**Comment by Drexell** [comment]
ok i will keep checking in to see if theres any progress.  thanks for looking into it :)

**Comment by RednedEpic** [comment]
No problem.

**Comment by Drexell** [comment]
just checking in to see if theres an update. :)

**Comment by Drexell** [comment]
bump :P

**Comment by Drexell** [comment]
Hello again I wanted to check in your probably busy working on other stuff atm and i know my request is small at that but its the one thing keeping my server from working the way I would like it to.  Hope to see an update soon thanks again :D

**Comment by Drexell** [comment]
Hello its beena  while just checking to see if this issue was ever looked at

**Comment by RednedEpic** [comment]
Haven’t checked this issue tracker in a while... I do recall trying to implement this, but ran into some problems. If I have some spare time soon, I may attempt to implement this.

**Comment by Drexell** [comment]
oh wow this was so long ago but at the same time I am very much still
interested in this being implemented.  If I recall correctly what happens
with phat loot is the chest animation is bypassed and goes directly to the
phat loot table.  This causes the chest not to open and if its a trapped
chest no signal will be produced.  All that needs to happen is a check to
see if the chest is redstone or not and produce a signal accordingly if it
is.  The animation itself isnt really an issue unless its needed to trigger
the redstone.  I am out most today and tomorrow but let me know if you try
something and I will dust my server off and try it out again.

**Comment by RednedEpic** [comment]
Just tested with PhatLoots... trapped chest redstone signal is already implemented.

**Comment by RednedEpic** [comment]
Latest commit should resolve this problem. Let me know if you are still encountering problems.

**Comment by Drexell** [comment]
Thank you for getting to this issue for me I will be trying it out soon and
will give you feedback to follow

**Comment by Drexell** [comment]
Sorry to bother you again so soon lol but im having trouble finding your
latest commit for phatloots to test my issue out.

**Comment by RednedEpic** [comment]
> Sorry to bother you again so soon lol but im having trouble finding your latest commit for phatloots to test my issue out.
> […](#)

What do you mean exactly? Just cloning the repo and using maven to compile it should work fine. If you need a jar directly, contact me on Discord: Redned#9473

**Comment by Drexell** [comment]
Hi I tried to find you on discord but your name isnt popping up.  Im sorry
to bother you as I have been out of the minecraft game for over a year now
and havent used the compile method to create a jar yet.  my discord is
Drexll#7719 msg anytime on your convenience no rush.
