### ISSUE TITLE
craftbukkit server console error

### ISSUE THREAD

**Issue by LastTulare** [RednedEpic/PhatLoots#13]
I was using Codisimus's latest release for my new 1.14.4 craftbukkit server, and it would load fine, and a lot of it worked, commands worked. Couldnt link loot to chests without getting errors. I found version 5.3.10, put it in, and it doesnt load when starting the server.

18.09 12:54:57 [Server] Server thread/INFO Enabling PhatLoots v5.3.10
18.09 12:54:57 [Server] Server thread/ERROR Error occurred while enabling PhatLoots v5.3.10 (Is it up to date?)
18.09 12:54:57 [Server] INFO java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
18.09 12:54:57 [Server] INFO at com.codisimus.plugins.phatloots.PhatLoots.onEnable(PhatLoots.java:153) ~[?:?]
18.09 12:54:57 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit_1.14.4.jar:git-Bukkit-6ed8a18]
18.09 12:54:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344) [craftbukkit_1.14.4.jar:git-Bukkit-6ed8a18]
18.09 12:54:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [craftbukkit_1.14.4.jar:git-Bukkit-6ed8a18]
18.09 12:54:57 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:447) [craftbukkit_1.14.4.jar:git-Bukkit-6ed8a18]
18.09 12:54:57 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:373) [craftbukkit_1.14.4.jar:git-Bukkit-6ed8a18]
18.09 12:54:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [craftbukkit_1.14.4.jar:git-Bukkit-6ed8a18]
18.09 12:54:57 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:253) [craftbukkit_1.14.4.jar:git-Bukkit-6ed8a18]
18.09 12:54:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:753) [craftbukkit_1.14.4.jar:git-Bukkit-6ed8a18]

**Comment by RednedEpic** [comment]
Use Spigot or Paper. Craftbukkit isn’t supported.

**Comment by LastTulare** [comment]
lol well then, Im gonna google paper, because I just got back into minecraft since I stopped using craftbukkit 1.8. 5 years ago. I never heard of paper. Ive heard of Spigot and tekkit. Thanks for the quick reply.

**Comment by RednedEpic** [comment]
> lol well then, Im gonna google paper, because I just got back into minecraft since I stopped using craftbukkit 1.8. 5 years ago. I never heard of paper. Ive heard of Spigot and tekkit. Thanks for the quick reply.

Spigot is a fork of Craftbukkit, so all Bukkit plugins will work with it and Paper is a fork of Spigot with loads of performance enhancements (recommended if you’re on 1.13 or 1.14).
