### ISSUE TITLE
Having trouble with Maven

### ISSUE THREAD

**Issue by shobzane** [RednedEpic/PhatLoots#3]
Hi, I've been trying to compile the code with Maven but I keep getting build failures. What command should I use in the directory or could you possibly send me the .jar file? I could pay you for it!

Thanks,
-Zane

**Comment by CaszGamerMD** [comment]
Mythicmobs and mythic drops files are missing, I'm currently working on an update with a friend and we have to remove some mythic mob in mythic drop stuff because the api is no longer online

**Comment by RednedEpic** [comment]
Sorry I’ve not checked this issue tracker in a while. It may be a bit late now, but yes, I can provide a jar. Just dm me on Discord, Redned#9473

**Comment by RednedEpic** [comment]
It appears the original issue was that PhatLoots could not find the WorldEdit/WorldGuard files in sk89q's repo, which may be an issue on your end. However I did notice some problems with MythicDrops repo and I got that sorted out.

Should be fixed in af6d618fbff0baf3a35c526feab633889b58608c.

**Comment by RednedEpic** [comment]
Cleaned out local maven repo and was able to build this perfectly fine. Noticed RegionTools was missing and added that to the lib yesterday. If anyone else encounters the same or a similar problem, please create a new issue.
