### ISSUE TITLE
1.17 Support

### ISSUE THREAD

**Issue by jonaas13** [RednedEpic/PhatLoots#32]
Current version of plugin loads no problem.
When opening a chest however error: Could not pass event InventoryCloseEvent to PhatLoots v5.4.2. ( Cannot invoke "Object.getClass()" because "obj" is null at....)
Chest remains empty to items, but the chest is still linked etc.
When will this be fixed and updated support to 1.17(.1)?

**Comment by RednedEpic** [comment]
This has been implemented :)
