### ISSUE TITLE
Anvil GUI for text input doesn't work in 1.14

### ISSUE THREAD

**Issue by RednedEpic** [RednedEpic/PhatLoots#7]
As the title says, entering text in an anvil using 1.14 with PhatLoots does not work.

https://pastebin.com/h0gTC8gs

Reflection methods being used appear to be outdated. Might swap to an NMS module system instead.

**Comment by CaszGamerMD** [comment]
otherwise most plugs now just use chat input from user

**Comment by RednedEpic** [comment]
Most likely what I’ll do instead.

**Comment by RednedEpic** [comment]
Resolved in 9df01f96164284b651ddb3cbf1dd6a6aa259f0e0.
